version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
    - location: scripts/start-server.sh
      timeout: 300

      
